#%RAML 1.0

# AMWA NMOS System Resource API
# (c) AMWA 2018

title: System
baseUri: http://example.api.com/x-nmos/system/{version}
version: v1.0
mediaType: application/json

documentation:
  - title: Overview
    content: |
      The System Resource API allows Nodes to obtain information that is common across a System
